# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'practiceeg' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
pod 'AgoraAudio_iOS', '~> 3.0.0'
pod 'AgoraRtcEngine_iOS', '~> 2.9.0'

  # Pods for practiceeg

  target 'practiceegTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'practiceegUITests' do
    # Pods for testing
  end



end
